### ISSUE TITLE
Поиск

### ISSUE THREAD

**Issue by ghost** [tretyakovsa/jaluzi#1]
Здравствуйте.
Залил в устройства ФС и прошивку как в видео, устройства подключились к модему, видны в сетевом окружении... но поиск между собой не работает.
Нажимаю на кнопку поиска устройств, находится только локальное устройство, остальных нет в списке.

**Comment by tretyakovsa** [comment]
Очень интересно. 
Сделайте запрос: /devices.scan.json
Придет ответ ОК.
Затем сделайте запрос: /devices.list.json
Ответом должен быть json вида: [{"ip":"192.168.0.101"},{"ip":"192.168.0.106"}] Ip адреса всех устройств в вашей сети. Сообщите работает или нет. И что возвращает?

**Comment by ghost** [comment]
После devices.scan.json OK приходит.
Ответ [{"ip":"192.168.1.10"}] (это локальное устройство).
Потом ни с того ни с сего поиск заработал (ночь в выключенном состоянии побыли устройства).
Но поиск работает как то коряво, не всегда устройства то ли отвечают, то ли слушает как то неправильно, очень много устройств не находится. Из 10 в среднем находится 4-6.
Я для теста обмен потом в терминал вывел, так и пакеты не приходят от других устройств. К сравнению принтер и модем отвечают практически мгновенно после нажатия кнопки поиск, а ESP чего то ждут...
Но я так понимаю это уже проблема в библиотеке SSDP и возможно недоработк самих модулей производителем. Как вы считаете?

**Comment by tretyakovsa** [comment]
Посмотрим и перепишем код поиска. Скорее всего можно улучшить результаты.

**Comment by ghost** [comment]
Спасибо, было бы очень неплохо!

**Comment by ghost** [comment]
Кстати я попробовал раскомментировать раздел <iconList> в ESP8266SSDP.cpp, добавил картинки как там нужно (48х48 icon48.png и 120х120 icon48.png), но к сожалению в сетевом окружении иконки устройств не меняются, остаются те, что по умолчанию в самой винде. Будет время, гляньте пожалуйста.
