### ISSUE TITLE
А можно расписать подробности по железу?

### ISSUE THREAD

**Issue by a-x-** [tretyakovsa/jaluzi#6]
Круто! Тоже делаю подобные штуки. 

Можете добавить в ридми своих проектов схемы, PCB, список деталей с ссылками на магазины...
И более подробно описание их совместной работы. Более подробные описания скриншотов и функций. 

Очень интересно какие конкретно движки использованы. 
Вы делали на серво/ШД регулировку температуры батарей? Какой крутящий момент примерно нужен? Нет никаких ручных весов, не могу нормально прикинуть.

**Comment by renat2985** [comment]
https://youtu.be/oTfA9c2-ztM

**Comment by a-x-** [comment]
Спасибо, но в виде текста было бы удобнее.

**Comment by a-x-** [comment]
И ссылку на видео в ридми было бы полезно наверно оставить.

**Comment by renat2985** [comment]
На главной странице репозитория есть достаточно подробное фото с тем куда что и как подключать. Будьте вниматльней. Оставлять ссылки на товары не целесообразоно т.к. товары быстро заканчиваются. Да и драйверы моторов и сами моторы можно использовать разные.
К тому же в видео все подробно рассказано и описано. Если у вас есть время сделайте по видео документацию в текстовом виде.
Более последнюю версию проекта Жалюзи можно скачать тут: https://github.com/tretyakovsa/Sonoff_WiFi_switch

Так же все техничекие вопросы лучше пишите туда.
